image: python:3.6

before_script:
  - python --version
  - pip install "poetry==1.0.5"

stages:
  - test

test:
  stage: test
  script:
  - cd common
  - poetry install
  - poetry run python -m unittest discover tests/unittests
