[default]
CAMERA = 'RASPI_V2'

MODEL_NAME = 'robots/TRT_ssd_mobilenet_v2_roco.bin'
OBJECTS_DETECTION_MODEL = "ssd_mobilenet_v2_roco_2018_03_29_20200314_015411_TWITCH_TEMP_733_IMGS_29595steps"

[development]

[production]
